// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNYLx3iyDaJy-n2d4T2xgd38rsA7vBZM',
    appId: '1:296536640003:android:456692085799c19bb25c36',
    messagingSenderId: '296536640003',
    projectId: 'flutter-ecomapp-dev-c7f8b',
    storageBucket: 'flutter-ecomapp-dev-c7f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjKvMIIH3bNGXDSfXMvOV405gi52Hkt4',
    appId: '1:296536640003:ios:3927b36843a71d1db25c36',
    messagingSenderId: '296536640003',
    projectId: 'flutter-ecomapp-dev-c7f8b',
    storageBucket: 'flutter-ecomapp-dev-c7f8b.appspot.com',
    iosClientId: '296536640003-sk03h0f68lupannm3j1s1j8coqsq0e9l.apps.googleusercontent.com',
    iosBundleId: 'dev.rdewan.ecomApp.development',
  );
}
