// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_qa.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class QaFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpnu1ULkph4gRIgxMYBPTbvahZjATaTW0',
    appId: '1:145803795125:android:cb44e5602fc482a11bfcfc',
    messagingSenderId: '145803795125',
    projectId: 'flutter-ecomapp-qa-92e63',
    storageBucket: 'flutter-ecomapp-qa-92e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJf77BhX9SSV09oVaYszMKo7Vm41dy4c',
    appId: '1:145803795125:ios:7172550170d0407a1bfcfc',
    messagingSenderId: '145803795125',
    projectId: 'flutter-ecomapp-qa-92e63',
    storageBucket: 'flutter-ecomapp-qa-92e63.appspot.com',
    iosClientId: '145803795125-3tsj10t1amp62d9fnof3j2vmuvj70lo8.apps.googleusercontent.com',
    iosBundleId: 'dev.rdewan.ecomApp.qa',
  );
}
