// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrLi7UYcOj3n3Iepc4LD1AHi5mEVR_bSM',
    appId: '1:316125087690:android:153ee22b421aac20f2f133',
    messagingSenderId: '316125087690',
    projectId: 'flutter-ecomapp-prod-34d00',
    storageBucket: 'flutter-ecomapp-prod-34d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJSwTTHnjpPSbjww7S7nWTa6AMWT8m_I',
    appId: '1:316125087690:ios:fa905992c2e9f3a7f2f133',
    messagingSenderId: '316125087690',
    projectId: 'flutter-ecomapp-prod-34d00',
    storageBucket: 'flutter-ecomapp-prod-34d00.appspot.com',
    iosClientId: '316125087690-vrqr63ua33klpl57gbpl73gkud78uj8f.apps.googleusercontent.com',
    iosBundleId: 'dev.rdewan.ecomApp',
  );
}
